### ISSUE TITLE
upgrade-acoustic-model annotation missing

### ISSUE THREAD

**Issue by paulcastro** [watson-developer-cloud/openwhisk-sdk#2]
The JSON file that annotates the upgrade-acoustic-model is missing in `annotations/speech-to-text-v1` in the master branch causing `python install.py` to fail.

Adding the file fixes the problem.

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by paulcastro** [comment]
@germanattanasio sure - it's an easy fix, though I'm not sure what should be in the annotations file.  I just submitted PR #3 , let me know if that works.
